---
name: Build master branch and upload

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - name: Show environment info
      run: dkp-pacman -Q

    - name: Checkout project
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build project
      run: make

    - name: Create release structure
      run: |
        mkdir -p release/switch/.overlays
        cp QuickNTP.ovl release/switch/.overlays/

    - name: Read app version from makefile
      run: |
        echo "version=$(make print-APP_VERSION)" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quickntp-${{ env.version }}
        path: release/
        include-hidden-files: true
